### ISSUE TITLE
Suggestion: Export classes on the package level

### ISSUE THREAD

**Issue by fschuetz04** [SanDisk-Open-Source/desmod#21]
Thanks for the library!
Though I only use `Queue` and `Pool` for now, it is really helpful.

However, I would propose to export such classes on the package level.

I do not want to pollute my namespace, as in:

```py
from desmod.queue import Queue

queue = Queue(env)
```

I do not see immediately from which package this class is.

But it is also a little bit weird to do it this way:

```py
import desmod.queue

queue = desmod.queue.Queue(env)
```

Why should I write queue twice?

I would propose to extend `__init__.py` and export classes like `Queue` on the package level:

```py
from .queue import Queue
```

Then I can do:

```py
import desmod

queue = desmod.Queue(env)
```

What are your thoughts?

**Comment by jpgrayson** [comment]
Hi @fschuetz04. Good question and I'm glad you're finding desmod's Queue to be useful enough to import!

The issue I have with reexporting `Queue` from the top-level `desmod` namespace is that I wouldn't know where to stop.

For example, just from `desmod.queue` there are several other classes that would be candidates for inclusion in the top-level namespace; would we want, for example, `PriorityQueue`? What about `QueueGetEvent` and friends? And then we'd want to similarly consider what other symbols from, e.g. `desmod.pool`, `desmod.simulation`, `desmod.config`, etc. belong in the top-level namespace. There may, in fact, be good choices for what to include or not include, but I've punted on making such decisions.

I'm not opposed with exporting various classes from the top-level `desmod` namespace. It would be helpful to have your opinion (and anyone else's) on what warrants being reexported in the `desmod` namespace. What criteria would you use to choose what to reexport?

**Comment by fschuetz04** [comment]
Sorry for the late reply.

I can understand your problem. Personally, I would go after what the user mostly uses (e.g. `Queue`, `PriorityQueue`, and `PriorityItem`, but not `QueueGetItem` etc.). The classes contained in the documentation would be a good starting point.

Personally, I also wouldn't mind if the package level contains many identifiers (still not that many compared to e.g. `numpy`). If that is a concern, I'm unsure how to decide which classes to include.
